#!/usr/bin/env python
"""Generate a sanitized production evidence bundle.

The bundle generator packages existing safe reports and optional readiness/status
endpoint snapshots. It never calls real providers, creates Zoom meetings, or
mutates application state.
"""

from __future__ import annotations

import argparse
import json
import platform
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit, urlunsplit
from urllib.request import Request, urlopen


SECRET_KEY_RE = re.compile(
    r"(secret|token|api[_-]?key|apikey|password|authorization|credential|signature|integration[_-]?key|cookie|database[_-]?url|redis[_-]?url)",
    re.IGNORECASE,
)
SECRET_QUERY_NAMES = {
    "token",
    "access_token",
    "refresh_token",
    "api_key",
    "apikey",
    "key",
    "password",
    "pwd",
    "signature",
    "integration_key",
    "integration-key",
    "sig",
}
SECRET_QUERY_RE = re.compile(
    r"([?&](?:token|access_token|refresh_token|api_key|apikey|key|password|pwd|signature|integration_key|integration-key|sig)=)[^&#\s]+",
    re.IGNORECASE,
)
BEARER_RE = re.compile(r"(Bearer\s+)[A-Za-z0-9._~+/=-]+", re.IGNORECASE)
AUTH_HEADER_RE = re.compile(r"(?i)(Authorization\s*:\s*)(?:Bearer\s+)?[^\s,;]+")
COOKIE_HEADER_RE = re.compile(r"(?i)((?:Cookie|Set-Cookie)\s*:\s*)[^\r\n;]+(?:;[^\r\n]*)?")
USERINFO_URL_RE = re.compile(r"([a-z][a-z0-9+.-]*://[^:/@\s]+:)[^/@\s]+(@)", re.IGNORECASE)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a sanitized production evidence bundle. Safe by default: no real "
            "provider calls, no Zoom calls, no state mutation."
        )
    )
    parser.add_argument("--base-url", default="http://127.0.0.1:8000", help="Application base URL used for optional safe checks.")
    parser.add_argument("--output-dir", default="tmp/production_evidence", help="Directory where the timestamped bundle folder is created.")
    parser.add_argument("--include-runtime-metrics", action="store_true", help="Fetch /api/metrics/runtime unless --no-network is set.")
    parser.add_argument("--include-config-check", action="store_true", help="Fetch /api/system/config-check unless --no-network is set.")
    parser.add_argument("--include-real-provider-report", help="Path to an existing real-provider E2E JSON report to sanitize and include.")
    parser.add_argument("--include-load-test-report", help="Path to an existing load-test JSON report to sanitize and include.")
    parser.add_argument(
        "--include-6-lessons-1000-ws-report",
        help="Path to an existing Stage 27B 6-lessons/1000-WebSocket mock load report to sanitize and include.",
    )
    parser.add_argument(
        "--include-6-lessons-1000-ws-analysis",
        help="Path to an existing Stage 27C 6-lessons/1000-WebSocket report analysis JSON to sanitize and include.",
    )
    parser.add_argument("--include-readiness-check", action="store_true", help="Fetch /api/health/ready unless --no-network is set.")
    parser.add_argument("--no-network", action="store_true", help="Package only local files and metadata; do not make HTTP requests.")
    parser.add_argument("--timeout", type=float, default=5.0, help="HTTP timeout in seconds for optional safe checks.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        result = generate_bundle(args)
    except Exception as exc:
        result = {"final_bundle_status": "failed", "error": _safe_error(exc)}
        print(json.dumps(sanitize_for_bundle(result), indent=2, ensure_ascii=False, sort_keys=True))
        return 1
    print(json.dumps(sanitize_for_bundle(result), indent=2, ensure_ascii=False, sort_keys=True))
    return 0 if result.get("final_bundle_status") != "failed" else 1


def generate_bundle(args: argparse.Namespace) -> dict[str, Any]:
    generated_at = datetime.now(timezone.utc).replace(microsecond=0)
    bundle_dir = _create_bundle_dir(Path(args.output_dir), generated_at)
    base_url = str(args.base_url).rstrip("/")

    included: list[str] = []
    missing: list[str] = []
    safety_notes = [
        "Generated by safe packaging script.",
        "No real provider calls are made by this script.",
        "No Zoom meetings are created by this script.",
        "Secrets and token-like values are redacted before writing artifacts.",
    ]

    environment = {
        "generated_at_utc": _timestamp(generated_at),
        "base_url": base_url,
        "no_network": bool(args.no_network),
        "network_checks_requested": {
            "readiness": bool(args.include_readiness_check),
            "runtime_metrics": bool(args.include_runtime_metrics),
            "config_check": bool(args.include_config_check),
        },
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "cwd": str(Path.cwd()),
    }
    _write_json(bundle_dir / "environment_summary.json", environment)
    included.append("environment_summary.json")

    if args.include_readiness_check:
        _include_safe_endpoint(
            bundle_dir=bundle_dir,
            base_url=base_url,
            endpoint="/api/health/ready",
            artifact_name="readiness_summary.json",
            timeout=args.timeout,
            no_network=args.no_network,
            included=included,
            missing=missing,
        )
    if args.include_runtime_metrics:
        _include_safe_endpoint(
            bundle_dir=bundle_dir,
            base_url=base_url,
            endpoint="/api/metrics/runtime",
            artifact_name="runtime_metrics_summary.json",
            timeout=args.timeout,
            no_network=args.no_network,
            included=included,
            missing=missing,
        )
    if args.include_config_check:
        _include_safe_endpoint(
            bundle_dir=bundle_dir,
            base_url=base_url,
            endpoint="/api/system/config-check",
            artifact_name="config_check_summary.json",
            timeout=args.timeout,
            no_network=args.no_network,
            included=included,
            missing=missing,
        )

    if args.include_real_provider_report:
        _include_existing_json_report(
            source=Path(args.include_real_provider_report),
            target=bundle_dir / "real_provider_e2e_report.json",
            artifact_name="real_provider_e2e_report.json",
            included=included,
            missing=missing,
        )
    if args.include_load_test_report:
        _include_existing_json_report(
            source=Path(args.include_load_test_report),
            target=bundle_dir / "load_test_report.json",
            artifact_name="load_test_report.json",
            included=included,
            missing=missing,
        )
    if getattr(args, "include_6_lessons_1000_ws_report", None):
        _include_existing_json_report(
            source=Path(args.include_6_lessons_1000_ws_report),
            target=bundle_dir / "load_test_6_lessons_1000_ws_report.json",
            artifact_name="load_test_6_lessons_1000_ws_report.json",
            included=included,
            missing=missing,
        )
    if getattr(args, "include_6_lessons_1000_ws_analysis", None):
        _include_existing_json_report(
            source=Path(args.include_6_lessons_1000_ws_analysis),
            target=bundle_dir / "load_test_6_lessons_1000_ws_analysis.json",
            artifact_name="load_test_6_lessons_1000_ws_analysis.json",
            included=included,
            missing=missing,
        )

    readme = bundle_readme()
    (bundle_dir / "README.md").write_text(readme, encoding="utf-8")
    included.append("README.md")

    manifest_artifacts = sorted([*included, "manifest.json"])
    manifest = {
        "generated_at_utc": _timestamp(generated_at),
        "base_url": base_url,
        "included_artifacts": manifest_artifacts,
        "missing_artifacts": sorted(missing),
        "load_test_6_lessons_1000_ws_report_included": "load_test_6_lessons_1000_ws_report.json" in included,
        "load_test_6_lessons_1000_ws_analysis_included": "load_test_6_lessons_1000_ws_analysis.json" in included,
        "safety_notes": safety_notes,
        "final_bundle_status": "partial" if missing else "complete",
        "sanitized": True,
    }
    _write_json(bundle_dir / "manifest.json", manifest)

    return {
        "bundle_dir": str(bundle_dir),
        "final_bundle_status": manifest["final_bundle_status"],
        "included_artifacts": manifest["included_artifacts"],
        "missing_artifacts": manifest["missing_artifacts"],
        "sanitized": True,
    }


def _include_safe_endpoint(
    *,
    bundle_dir: Path,
    base_url: str,
    endpoint: str,
    artifact_name: str,
    timeout: float,
    no_network: bool,
    included: list[str],
    missing: list[str],
) -> None:
    if no_network:
        missing.append(f"{artifact_name} (skipped: --no-network)")
        return
    started = time.perf_counter()
    try:
        payload = _fetch_json(urljoin(base_url.rstrip("/") + "/", endpoint.lstrip("/")), timeout=timeout)
        summary = {
            "endpoint": endpoint,
            "ok": True,
            "latency_ms": round((time.perf_counter() - started) * 1000, 2),
            "payload": payload,
        }
    except Exception as exc:
        summary = {
            "endpoint": endpoint,
            "ok": False,
            "latency_ms": round((time.perf_counter() - started) * 1000, 2),
            "error": _safe_error(exc),
        }
        missing.append(f"{artifact_name} (endpoint unavailable)")
    _write_json(bundle_dir / artifact_name, summary)
    included.append(artifact_name)


def _include_existing_json_report(
    *,
    source: Path,
    target: Path,
    artifact_name: str,
    included: list[str],
    missing: list[str],
) -> None:
    if not source.exists():
        missing.append(f"{artifact_name} (source missing: {source})")
        return
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
        _write_json(target, payload)
    except json.JSONDecodeError:
        sanitized_text = sanitize_for_bundle(source.read_text(encoding="utf-8"))
        target.write_text(str(sanitized_text), encoding="utf-8")
    included.append(artifact_name)


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(sanitize_for_bundle(payload), indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def sanitize_for_bundle(value: Any, key: str | None = None) -> Any:
    if key and SECRET_KEY_RE.search(key):
        return "[redacted]"
    if isinstance(value, dict):
        return {str(child_key): sanitize_for_bundle(child_value, str(child_key)) for child_key, child_value in value.items()}
    if isinstance(value, list):
        return [sanitize_for_bundle(item) for item in value]
    if isinstance(value, tuple):
        return [sanitize_for_bundle(item) for item in value]
    if isinstance(value, str):
        return _sanitize_string(value)
    return value


def _sanitize_string(value: str) -> str:
    sanitized = BEARER_RE.sub(r"\1<redacted>", value)
    sanitized = AUTH_HEADER_RE.sub(r"\1<redacted>", sanitized)
    sanitized = COOKIE_HEADER_RE.sub(r"\1<redacted>", sanitized)
    sanitized = USERINFO_URL_RE.sub(r"\1<redacted>\2", sanitized)
    sanitized = SECRET_QUERY_RE.sub(r"\1<redacted>", sanitized)
    return _sanitize_url_query(sanitized)


def _sanitize_url_query(value: str) -> str:
    try:
        parts = urlsplit(value)
    except ValueError:
        return value
    if not parts.scheme or not parts.netloc or not parts.query:
        return value
    query = []
    changed = False
    for key, item_value in parse_qsl(parts.query, keep_blank_values=True):
        if key.lower() in SECRET_QUERY_NAMES:
            query.append((key, "<redacted>"))
            changed = True
        else:
            query.append((key, item_value))
    if not changed:
        return value
    sanitized_url = urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))
    return sanitized_url.replace("%3Credacted%3E", "<redacted>")


def _fetch_json(url: str, *, timeout: float) -> Any:
    request = Request(url, headers={"Accept": "application/json", "User-Agent": "production-evidence-bundle/1.0"})
    with urlopen(request, timeout=timeout) as response:
        body = response.read()
    return json.loads(body.decode("utf-8"))


def _safe_error(error: Exception) -> str:
    if isinstance(error, HTTPError):
        return f"HTTP {error.code}"
    if isinstance(error, URLError):
        return error.reason.__class__.__name__ if hasattr(error, "reason") else "URL error"
    return error.__class__.__name__


def _create_bundle_dir(output_dir: Path, generated_at: datetime) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    base_name = _timestamp(generated_at).replace(":", "-")
    candidate = output_dir / base_name
    suffix = 1
    while candidate.exists():
        candidate = output_dir / f"{base_name}-{suffix}"
        suffix += 1
    candidate.mkdir(parents=True)
    return candidate


def _timestamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def bundle_readme() -> str:
    return """# Production Evidence Bundle

## What this bundle proves

This bundle proves that selected safe readiness, runtime, config, load-test, and real-provider report artifacts were collected into one sanitized folder at a specific time. It is useful for C# handoff, DevOps review, release readiness notes, and CI artifacts.

## What this bundle does not prove

The bundle is safe packaging. It does not itself prove real-provider success, Zoom behavior, provider quota headroom, or production load capacity unless the corresponding real-provider and load-test reports are included and were generated by approved manual runs.

## Mock load testing vs real-provider proof

Mock load tests validate application fanout paths, WebSocket behavior, Redis Pub/Sub counters, cache behavior, and runtime pressure without spending provider quota. Real-provider proof requires manual Stage 26F-H execution with explicit flags, quota guard confirmation, and operator review.

## Interpreting artifacts

- `manifest.json`: artifact inventory, safety notes, and `final_bundle_status`.
- `environment_summary.json`: bundle context and requested network mode. It does not include environment variables.
- `readiness_summary.json`: optional `/api/health/ready` snapshot.
- `config_check_summary.json`: optional `/api/system/config-check` snapshot.
- `runtime_metrics_summary.json`: optional `/api/metrics/runtime` snapshot.
- `real_provider_e2e_report.json`: optional sanitized Stage 26G/H report.
- `load_test_report.json`: optional sanitized mock or approved load-test report.
- `load_test_6_lessons_1000_ws_report.json`: optional Stage 27B mock fanout report for 6 simultaneous lessons and 1000 caption WebSocket clients.
- `load_test_6_lessons_1000_ws_analysis.json`: optional Stage 27C read-only analysis of the Stage 27B report.

## Why real-provider E2E must stay manual

Real-provider E2E can spend Azure, ElevenLabs, STT, Translator, or Zoom quota and depends on external availability. Keep it out of normal CI. Run it only with manual approval, explicit Stage 26F-H flags, and quota guard limits.
"""


if __name__ == "__main__":
    raise SystemExit(main())
